// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "mattermost-plugin-yandex-calendar",
    "name": "Yandex Calendar",
    "description": "Yandex Calendar integration via CalDAV (app password)",
    "homepage_url": "https://github.com/danilvalov/mattermost-plugin-yandex-calendar",
    "support_url": "https://github.com/danilvalov/mattermost-plugin-yandex-calendar/issues",
    "release_notes_url": "https://github.com/danilvalov/mattermost-plugin-yandex-calendar/releases/tag/v0.9.5",
    "icon_path": "assets/profile-ycal.svg",
    "version": "0.9.5+495f33c",
    "min_server_version": "10.7.0",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "AdminUserIDs",
                "display_name": "Admin User IDs:",
                "type": "text",
                "help_text": "List of users authorized to administer the plugin in addition to the System Admins. Must be a comma-separated list of user IDs.\\n \\n User IDs can be found in **System Console \u003e User Management \u003e Users**. Select the user's name, and the ID is displayed in the top-right corner of the banner.",
                "placeholder": "",
                "default": null,
                "hosting": "",
                "secret": false
            },
            {
                "key": "AdminLogLevel",
                "display_name": "Copy plugin logs to admins, as bot messages:",
                "type": "dropdown",
                "help_text": "Select the log level.",
                "placeholder": "",
                "default": "none",
                "options": [
                    {
                        "display_name": "None",
                        "value": "none"
                    },
                    {
                        "display_name": "Debug",
                        "value": "debug"
                    },
                    {
                        "display_name": "Info",
                        "value": "info"
                    },
                    {
                        "display_name": "Warning",
                        "value": "warn"
                    },
                    {
                        "display_name": "Error",
                        "value": "error"
                    }
                ],
                "hosting": "",
                "secret": false
            },
            {
                "key": "AdminLogVerbose",
                "display_name": "Display full context for each admin log message:",
                "type": "bool",
                "help_text": "",
                "placeholder": "",
                "default": false,
                "hosting": "",
                "secret": false
            },
            {
                "key": "EnableCalendarUI",
                "display_name": "Enable Calendar product UI:",
                "type": "bool",
                "help_text": "When enabled, the Calendar product is shown in the Mattermost product switcher (left sidebar). Disable to hide the UI while keeping slash commands and notifications. Requires a page reload for users after changing.",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "EncryptionKey",
                "display_name": "Encryption key",
                "type": "generated",
                "help_text": "**Required**: The encryption key used to store user credentials and data. If this is regenerated all user authentication data will be lost and users will need to reconnect.",
                "placeholder": "",
                "default": null,
                "hosting": "",
                "secret": true
            }
        ],
        "sections": null
    }
}
`);

export default manifest;
